const Validator = require('../src/wallet_address_validator.js')
console.log(Validator.validate('tz1KqTpEZ7Yob7QbPE4Hy4Wo8fHG8LhKxZSx', 'xtz'))
console.log(Validator.validate('tz1gjaF81ZRRvdzjobyfVNsAeSC6PScjfQwN', 'xtz'))
console.log(Validator.validate('tz1czdxQ2MdazRpTNcQHzoXiWL6cdXVKKyEs', 'xtz'))
console.log(Validator.validate('tz1er9zBo3p2K6fY5qo8wE5C7MQMpWmLU5cS', 'xtz'))
console.log(Validator.validate('tz1Kph3wTxQ7B75AVJCRH5RLG7YKt79MTxZz', 'xtz'))
console.log(Validator.validate('tz1S2ZjS9zQuXQvtmE3QFx73myVXa83Rdt57', 'xtz'))
console.log(Validator.validate('tz1RtJciYyd1PdVjrai1vxGUuLXX9orMRB5y', 'xtz'))
