const Validator = require('../src/wallet_address_validator.js')
console.log(Validator.validate('AXu57dhdNDnA5drqJUM2KfoMqgaLwmZwoP', 'ont'))
console.log(Validator.validate('TNVv2v7eKL525gZ2YCmFnsB2FGNG4VeMHX', 'ont'))
console.log(Validator.validate('TFYhfePLaZq1Y4BdKAnorm3XjjqTZcc9m4', 'ont'))
console.log(Validator.validate('AecjXQsLGsSU3nmx92UuGGbF1fj7EsGrt2', 'ont'))
