---
ignorePatterns:
  - '*.d.ts'
  - 'dist'
  - 'rollup.config.ts'

env:
  browser: true

extends:
  - plugin:prettier/recommended

parser: '@typescript-eslint/parser'

parserOptions:
  project: './tsconfig.json'
  sourceType: module

settings:
  import/internal-regex: ^@ramp-instant/

plugins:
  - eslint-plugin-import
  - simple-import-sort
  - eslint-plugin-prettier

rules:
  arrow-parens:
    - off
    - always
  comma-dangle: 0
  no-empty: error
  import/no-extraneous-dependencies: error
  no-restricted-imports:
    - error
    - patterns:
        - '../*' # forbid parent-relative imports

  simple-import-sort/imports:
    - error
    - groups: # see https://github.com/lydell/eslint-plugin-simple-import-sort#custom-grouping
        - ["^@?\\w"] # regular npm packages
        - ["^\\."] # sibling files
