
# .buildkite/pipeline.yml
steps:
  - label: ":sonarqube: Sonarqube"
    plugins:
      - wayfair-incubator/sonarscanner#v0.1.1:
          sonarqube_host:  http://44.195.78.66:9000
          project_key: CryptoAddressValidator
          additional_flags: -Dsonar.ws.timeout=120
    soft_fail: # Ensures a Sonarqube error does not fail the pipeline
      - exit_status: "*"